### ISSUE TITLE
Could not get unknown property 'manifestOutputDirectory' for task '<yourTask>' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.

### ISSUE THREAD

**Issue by mathieudebrito** [pranay1494/DynamicDeeplink#1]
Hello ! 

I followed your blog article on https://medium.com/swlh/generating-deeplinks-dynamically-in-android-ebe503e7241f 
but ran into this exception : 

`Could not get unknown property 'manifestOutputDirectory' for task '<yourTask>' of type com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest.`

**Comment by mathieudebrito** [comment]
We can fix this by simply replacing `def manifestDirPath = manifestOutputDirectory.asFile.get()` by `def manifestDirPath = multiApkManifestOutputDirectory.asFile.get()`

**Comment by zyw745293** [comment]
> We can fix this by simply replacing `def manifestDirPath = manifestOutputDirectory.asFile.get()` by `def manifestDirPath = multiApkManifestOutputDirectory.asFile.get()`

Hi, can you tell me which file to replace these?

**Comment by mathieudebrito** [comment]
@zyw745293 in `deeplink_config.gradle`
